# Generated by Django 5.0.4 on 2024-05-05 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_question_choice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_name',
            new_name='title',
        ),
    ]
