# Generated by Django 5.0.4 on 2024-05-06 21:35

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_slide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='file',
            field=models.FileField(upload_to=courses.models.media_upload_to),
        ),
    ]
