# Generated by Django 5.0.4 on 2024-05-08 22:32

import courses.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_slide_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slide',
            name='file',
        ),
        migrations.AddField(
            model_name='module',
            name='content_type',
            field=models.CharField(choices=[('SL', 'Slides'), ('VD', 'Video'), ('BT', 'Both')], default='SL', max_length=2),
        ),
        migrations.AddField(
            model_name='slide',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=courses.models.media_upload_to),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('video_file', models.FileField(upload_to=courses.models.media_upload_to)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='courses.module')),
            ],
        ),
    ]
