# Generated by Django 5.0.4 on 2024-05-17 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_slide_options_slide_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
