# Generated by Django 5.0.4 on 2024-05-23 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_delete_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermoduleprogress',
            name='slides_viewed',
            field=models.JSONField(default=list),
        ),
    ]
