# Generated by Django 5.0.4 on 2024-05-25 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_usermoduleprogress_slides_viewed'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhishingEmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('sender', models.CharField(max_length=255)),
            ],
        ),
    ]
